# 服务端口
server:
  port: 8110

# 环境设置
spring:
  profiles:
    active: dev
  # 服务名
  application:
    name: service-core
  # mysql数据库连接
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: nawiew
  #spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
#mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/nawiew/srb/core/mapper/xml/*.xml
#spring:
redis:
  host: 127.0.0.1
  port: 6379
  database: 0
  #password: 123456 #默认为空
  timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
  lettuce:
    pool:
      max-active: 20  #最大连接数，负值表示没有限制，默认8
      max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
      max-idle: 8     #最大空闲连接，默认8
      min-idle: 0     #最小空闲连接，默认0