server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

#spring:
redis:
  host: 127.0.0.1
  port: 6379
  database: 0
  #password: 123456 #默认为空
  timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
  lettuce:
    pool:
      max-active: 20  #最大连接数，负值表示没有限制，默认8
      max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
      max-idle: 8     #最大空闲连接，默认8
      min-idle: 0     #最小空闲连接，默认0

#阿里云短信
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: LTAI5tBX82sQAbEyughogcpi
    key-secret: g7bKTY8DxzDSIUkyYsa3ncHrZmlCKV
    template-code: SMS_217425770
    sign-name: 北京课时教育
feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  #开启Feign对Sentinel的支持
  #feign:
  sentinel:
    enabled: true